### ISSUE TITLE
Posting formdata

### ISSUE THREAD

**Issue by blocknotes** [sdogruyol/spec-kemal#11]
I'm trying to test a formdata post route:
```
    post "/user" do |env|
      p env.params.body  # empty !
      env.params.body
    end
    post("/user", headers: nil, body: "name=Boh&age=123")
    response.body.should eq("name=Boh&age=123")
```
But body is empty... am I missing something?

**Comment by sdogruyol** [comment]
Yes, you're missing the `"Content-Type" => "application/x-www-form-urlencoded"` header in your request.

**Comment by blocknotes** [comment]
Thank you @sdogruyol
