### ISSUE TITLE
Duplicate trail found

### ISSUE THREAD

**Issue by blocknotes** [sdogruyol/spec-kemal#12]
I have 2 specs files with a get "/" route.
When I execute `crystal spec` I get an error: `Duplicate trail found 'get/'`

It seems like the old routes are not removed between specs.
You can reproduce the error by creating another spec in the specs of spec-kemal.
For example (*spec/spec-kemal2_spec.cr*):

       require "./spec_helper"
       describe "SpecKemalApp2" do
         it "handles get (2)" do
           get "/" do
             "Hello world..."
           end
           get "/"
           response.body.should eq "Hello world..."
         end
       end

Stack trace:

       Duplicate trail found 'get/'
       0x10bd7f785: *CallStack::unwind:Array(Pointer(Void)) at ??
       0x10bd7f721: *CallStack#initialize:Array(Pointer(Void)) at ??
       0x10bd7f6f8: *CallStack::new:CallStack at ??
       0x10bd7a905: *raise<Radix::Tree::DuplicateError>:NoReturn at ??
       0x10beb8990: *Radix::Tree(Kemal::Route)@Radix::Tree(T)#add<String, Kemal::Route, Radix::Node(Kemal::Route)>:(Array(Radix::Node(Kemal::Route)) | Kemal::Route | Nil) at ??
       0x10beb8706: *Radix::Tree(Kemal::Route)@Radix::Tree(T)#add<String, Kemal::Route, Radix::Node(Kemal::Route)>:(Array(Radix::Node(Kemal::Route)) | Kemal::Route | Nil) at ??
       0x10beb8097: *Radix::Tree(Kemal::Route)@Radix::Tree(T)#add<String, Kemal::Route>:(Array(Radix::Node(Kemal::Route)) | Kemal::Route | Radix::Node(Kemal::Route) | Nil) at ??
       0x10beb78e7: *Kemal::RouteHandler#add_to_http_radix_tree<String, String, Kemal::Route>:(Array(Radix::Node(Kemal::Route)) | Kemal::Route | Radix::Node(Kemal::Route) | Nil) at ??
       0x10beb767e: *Kemal::RouteHandler#add_http_route<String, String, &Proc(HTTP::Server::Context, String)>:(Array(Radix::Node(Kemal::Route)) | Kemal::Route | Radix::Node(Kemal::Route) | Nil) at ??
       0x10bd7a662: *get<String, &Proc(HTTP::Server::Context, String)>:(Array(Radix::Node(Kemal::Route)) | Kemal::Route | Radix::Node(Kemal::Route) | Nil) at ??
       0x10bd7d8ba: ~procProc(Nil)@spec/spec-kemal_spec.cr:4 at ??
       0x10bd7d3ab: *it<String, String, Int32, Int32, &Proc(Nil)>:(Array(Spec::Result) | Nil) at ??
       0x10bd7d830: ~procProc(Nil)@spec/spec-kemal_spec.cr:3 at ??
       0x10be16352: *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
       0x10bd7d7b9: *describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
       0x10bd61015: __crystal_main at ??
       0x10bd75bb8: main at ??

**Comment by blocknotes** [comment]
I don't know if there are better solutions but I solved changing the after_each with:
```
Spec.after_each do
  Kemal.config.clear
  Kemal::RouteHandler::INSTANCE.http_routes = Radix::Tree(Kemal::Route).new
end
```
Useful reference here: [spec_helper](https://github.com/kemalcr/kemal/blob/master/spec/spec_helper.cr#L82)

**Comment by sdogruyol** [comment]
`spec-kemal` is meant to be used for testing out the routes your app currently have.

**Comment by carcinocron** [comment]
for `spec/spec_helper.cr` I try:
```
require "spec"
require "../src/kemalpbb"

Spec.after_each do
  Kemal.config.clear
  Kemal::RouteHandler::INSTANCE.http_routes = Radix::Tree(Kemal::Route).new
end
```
but get:
```
In spec/spec_helper.cr:6:33

 6 | Kemal::RouteHandler::INSTANCE.http_routes = Radix::Tree(Kemal::Route).new
                                   ^----------
Error: undefined method 'http_routes=' for Kemal::RouteHandler
```
