### ISSUE TITLE
Get session_id data for subsequent requests

### ISSUE THREAD

**Issue by MisterBianco** [sdogruyol/spec-kemal#13]
I realize this is a noob question, however after about an hour struggling I have to ask.

If I have a route say:

```
/Login/
```

Which when posted to correctly generates session data including a cookie how can I use that cookie in subsequent requests.

I was hoping for an easier method than

```
response.headers.get?("Set-Cookie") + parse
```

If there isn't then I would like to raise a feature request and if there is then please help me out :smile:

My test flow will look like

- Call /login/ for session data
- Call /protected/ route with session data succeeds
- Call /logout/ and destroys session
- Call /protected/ and expect a failure

**Comment by sdogruyol** [comment]
Your specs should be stateless and you can use `Spec.before_each` to actually call `/login` and get that cookie for every spec you have. I'm not sure about how can we make this a built-in feature :thinking:

**Comment by MisterBianco** [comment]
Thank you for answering, so if in one "test" case I make a call to login, is the session_id saved to that tests "session"

IE
If I make the call to /login/ and it returns with a session cookie can I make the call to /protected/ and that request will use the session of the previous request automatically?
