### ISSUE TITLE
Release 0.4.0 has invalid shards.yml

### ISSUE THREAD

**Issue by peterhoeg** [sdogruyol/spec-kemal#14]
The version in shards.yml is still 0.3.0 making it impossible to use version 0.4.0 as shards will continuously complain that ```Dependencies aren't satisfied. Install them with 'shards install'```.

Suggested fix: Bump version to 0.4.1 and update shards.yml accordingly.

**Comment by sdogruyol** [comment]
Fixed via https://github.com/kemalcr/spec-kemal/releases/tag/v0.5.0
