### ISSUE TITLE
cannot get appropriate `response`

### ISSUE THREAD

**Issue by jney** [sdogruyol/spec-kemal#3]
hi. i'm pretty new to crystal and using kemal for the first time.
i wanted to test my code, but i always got the following response whatever the code is:

``` crystal
puts response.inspect
# => #<HTTP::Client::Response:0x109148e60 @version="HTTP/1.1", @status_code=200, @status_message="OK", @headers=HTTP::Headers{"Connection" => "keep-alive", "X-Powered-By" => "Kemal", "Content-Type" => "text/html", "Content-Length" => "0"}, @body_io=nil, @cookies=nil, @computed_content_type_header=nil, @body="">
```

did i miss something?

**Comment by sdogruyol** [comment]
Fixed as of https://github.com/sdogruyol/spec-kemal/commit/f2659b06fd5129d81e7d332ebb7ccd9fad3ca25f
