### ISSUE TITLE
Clearing settings between specs

### ISSUE THREAD

**Issue by jwoertink** [sdogruyol/spec-kemal#9]
Kemal has a `Kemal.config.clear` which looks to reset handlers and such. This is pretty much what I'm looking for; however, when I add this, things blow up. 

How I added it
```crystal
# spec_helper.cr
Spec.after_each do
  Kemal.config.clear 
end
```

The error I get
```text
Index out of bounds
0x10c5e6922: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10c5e68c1: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10c5e6898: *CallStack::new:CallStack at ??
0x10c5d4481: *raise<IndexError>:NoReturn at ??
0x10c6f177f: *Array(HTTP::Handler)@Indexable(T)#first:HTTP::Handler at ??
0x10c5e3f30: *build_main_handler:HTTP::Handler at ??
0x10c5e3b91: *process_request<HTTP::Request>:HTTP::Client::Response at ??
0x10c5e3b34: *get<String>:HTTP::Client::Response at ??
0x10c5e4794: ~procProc(Nil)@spec/integration_spec.cr:19 at ??
0x10c5e0437: *it<String, String, Int32, Int32, &Proc(Nil)>:(Array(Spec::Result) | Nil) at ??
0x10c5e3a09: ~procProc(Nil)@spec/integration_spec.cr:13 at ??
0x10c666f62: *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x10c5e4969: *describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x10c5e4959: *context<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x10c5e3904: ~procProc(Nil)@spec/integration_spec.cr:11 at ??
0x10c666f62: *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x10c5e4969: *describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x10c5c9a13: __crystal_main at ??
0x10c5da988: main at ??
```

The spec that throws this error passes when I remove that after_each block. I've tried `before_each` too, but the same error happens. 

It would be cool if spec-kemal just handled this automatically, or at least with a configure option like:

```crystal
SpecKemal.configure do |c|
  c.clear_between_specs = true
end
```

**Comment by jwoertink** [comment]
Actually, scratch that. It turns out this was because I was doing an integration test, and actually running Kemal in test mode during specs. So I ended up doing this in my spec

```crystal
Spec.before_each do
  Kemal.config.logging = false
  Kemal.config.logger = Kemal::NullLogHandler.new
  Kemal.run
end
Spec.after_each do
  Kemal.stop
  Kemal.config.clear
end
```

but I still think it would be cool if spec-kemal handled some of this for me. Not sure if it's possible with Spec, but with RSpec inside of rails, you know how you can do 

```ruby
RSpec.describe SomeController, type: :controller
```

It would be sweet if you could hook in to it that way so you could do

```crystal
describe SomeApp, type: :kemal
```

or whatever... and then by having that option added, it just knows to boot and stop kemal between specs, and clear all the settings and stuff.

**Comment by sdogruyol** [comment]
With https://github.com/crystal-lang/crystal/pull/8302, this is gonna be possible :pray:

**Comment by jwoertink** [comment]
Yeah! 😂

**Comment by henrikac** [comment]
@jwoertink @sdogruyol 
I'm not sure if this is still an issue but could a possible solution be to extend the built-in `Spec.after_each`?

```crystal
module Spec
  def self.after_each(&block)
    root_context.after_each(&block)
    # extend self.after_each with some kind of
    # cleaning up logic
    if clear_between_specs
      Kemal.config.clear
    end
  end
end
```

**Comment by jwoertink** [comment]
I think this issue is actually resolved now. Back when I originally posted this, `Spec` was a bit limited. There's lots of hooks, and you can tag specs and such. I don't think it would be too difficult to handle this now. Thanks for the ping @henrikac
